@startuml name
class Conta {
    - numeroConta : int
    - nomeTitular : string
    - saldo : float
    + Conta(numeroConta: int, nomeTitular: string, saldo: float)
    + getNumeroConta() const : int
    + setSaldo(saldo: float) : void
    + getSaldo() const : float
    + setNomeTitular(nomeTitular: string) : void
    + getNomeTitular() const : string
    + emitirExtrato() const : void
}

class AbrirConta {
    - numeroConta : int
    - nomeTitular : string
    + solicitarDados() : void
    + abrir(contas: vector<Conta>&) : void
}

class DepositarNaConta {
    - valor : float
    - numeroConta : int
    + solicitarDados() : void
    + depositar(contas: vector<Conta>&) : void
}

class TransferirEntreContas {
    - valor : float
    - numeroContaOrigem : int
    - numeroContaDestino : int
    + solicitarDados() : void
    + transferir(contas: vector<Conta>&) : void
}

class SacarDaConta {
    - valor : float
    - numeroConta : int
    + solicitarDados() : void
    + sacar(contas: vector<Conta>&) : void
}


Conta "1..n" --> "1..n" AbrirConta
Conta "1..n" --> "1..n" DepositarNaConta
Conta "1..n" --> "1..n" TransferirEntreContas
Conta "1..n" --> "1..n" SacarDaConta

@enduml
