@startuml name

actor User

User -> AbrirConta: solicitarDados()
activate AbrirConta
AbrirConta -> Conta: Conta(numeroConta, nomeTitular, 0)
activate Conta
deactivate Conta
AbrirConta -> contas: insert(novaConta)
activate contas
deactivate contas
deactivate AbrirConta
AbrirConta --> User: Conta aberta
User -> DepositarNaConta: solicitarDados()
activate DepositarNaConta
DepositarNaConta -> contas: getNumeroConta()
activate contas
contas -> Conta: getNumeroConta()
activate Conta
Conta --> contas: numeroConta
deactivate Conta
contas --> DepositarNaConta: numeroConta
DepositarNaConta -> contas: setSaldo(saldoAtual + valor)
activate contas
contas -> Conta: setSaldo(saldoAtual + valor)
activate Conta
Conta --> contas: saldo
deactivate Conta
contas --> DepositarNaConta: Novo saldo
deactivate contas
DepositarNaConta --> User: Depósito realizado
User -> TransferirEntreContas: solicitarDados()
activate TransferirEntreContas
TransferirEntreContas -> contas: getNumeroConta()
activate contas
contas -> Conta: getNumeroConta()
activate Conta
Conta --> contas: numeroContaOrigem
deactivate Conta
contas --> TransferirEntreContas: numeroContaOrigem
TransferirEntreContas -> contas: getNumeroConta()
contas -> Conta: getNumeroConta()
activate Conta
Conta --> contas: numeroContaDestino
deactivate Conta
contas --> TransferirEntreContas: numeroContaDestino
TransferirEntreContas -> contas: setSaldo(saldoOrigem - valor)
activate contas
contas -> Conta: setSaldo(saldoOrigem - valor)
activate Conta
Conta --> contas: saldo
deactivate Conta
contas -> Conta: setSaldo(saldoDestino + valor)
activate Conta
Conta --> contas: saldo
deactivate Conta
deactivate contas
TransferirEntreContas --> User: Transferência realizada
User -> SacarDaConta: solicitarDados()
activate SacarDaConta
SacarDaConta -> contas: getNumeroConta()
activate contas
contas -> Conta: getNumeroConta()
activate Conta
Conta --> contas: numeroConta
deactivate Conta
contas --> SacarDaConta: numeroConta
SacarDaConta -> contas: setSaldo(saldoAtual - valor)
activate contas
contas -> Conta: setSaldo(saldoAtual - valor)
activate Conta
Conta --> contas: saldo
deactivate Conta
contas --> SacarDaConta: Novo saldo
deactivate contas
SacarDaConta --> User: Saque realizado
@enduml